import React, { useEffect, useState } from "react"; 
import { useParams } from "react-router-dom";
import ItemDetail from "../../components/ItemDetail/ItemDetail"
import "./ItemDetailContainer.css";

function getItem(id) {
    const myPromise = new Promise((resolve, reject) => {
        const productsList = [
            {id: 1, name: "En el bosque", autor: "Alysaa Wees", resume: 'En un reino lejano, una princesa rebelde debe elegir entre la libertad y la muerte. Pero se somete a un hechizo y duerme. Y en sus sueños, sueña un plan de revolución. En el bosque, una bruja solitaria arranca pétalos de su corazón para concederles a los niños sus más grandes deseos. Hasta que un zorro llega para contarle una historia. Una historia que la hará sangrar. Y, en nuestro mundo, Rhea sueña. Sueña con una escalera. Sueña con una puerta. Y, detrás de esa puerta, sueña con ella misma. Muerta. Cuando poco a poco su familia comience a desaparecer y su vida se ponga de cabeza, los límites entre la realidad y el sueño se volverán cada vez más difusos. ¡Un fantasy oscuro y adictivo con la cadencia de un sueño!', price: 1930, img:"/img/inicio1.jpg", stock: 10},
            {id: 2, name: "A Fuego Lento", autor: "Paula Hawkins", resume: 'Con la misma intensidad con la que ha cautivado a 27 millones de lectores en todo el mundo, la autora de La chica del tren, Paula Hawkins, nos ofrece un brillante thriller sobre las heridas que provocan los secretos que ocultamos. El descubrimiento del cuerpo de un joven asesinado brutalmente en una casa flotante de Londres desencadena sospechas sobre tres mujeres. Laura es la chica conflictiva que quedó con la víctima la noche en que murió; Carla, aún de luto por la muerte de un familiar, es la tía del joven, y Miriam es la indiscreta vecina que oculta información sobre el caso a la policía. Tres mujeres que no se conocen, pero que tienen distintas conexiones con la víctima. Tres mujeres que, por diferentes razones, viven con resentimiento y que, consciente o inconscientemente, esperan el momento de reparar el daño que se les ha hecho.', price: 2100, img:"/img/libro1.jpg", stock: 10},
            {id: 3, name: "Al Final Mueren Los Dos", autor: "Adam Silvera", resume: 'Imagina un mundo en el que una organización les avisa a las personas la inminencia de su muerte. Imagina que empezó la cuenta regresiva. Imagina cómo vivirías tu vida en solo un día. ¿Estarías listo para decir adiós? Al final mueren los dos es un canto a la fuerza arrolladora de la vida, que transformará para siempre tu forma de comprender el tiempo, la amistad y el amor.', price: 2050, img:"/img/libro24.jpg", stock: 10},
            {id: 4, name: "Nosotros En La Luna", autor: "Alice Kellen", resume: 'Cuando Rhys y Ginger se conocen en las calles de la ciudad de la luz, no imaginan que sus vidas se unirán para siempre, a pesar de la distancia y de que no puedan ser más diferentes. Ella vive en Londres y a veces se siente tan perdida que se ha olvidado hasta de sus propios sueños. Él es incapaz de quedarse quieto en ningún lugar y cree saber quién es. Y cada noche su amistad crece entre emails llenos de confidencias, dudas e inquietudes. Pero ¿qué ocurre cuando el paso del tiempo pone a prueba su relación? ¿Es posible colgarse de la luna junto a otra persona sin poner en riesgo el corazón? Una historia sobre el amor, el destino y la búsqueda de uno mismo.', price: 2250, img:"/img/oferta1.jpg", stock: 10},
            {id: 5, name: "El Engaño", autor: "Kiersten White", resume: 'Con la magia que extiende sus garras por las fronteras del reino de Arturo, el emblemático mago Merlín tiene una solución: decide enviar a Ginebra para que se convierta en la esposa de Arturo, para que pueda protegerlos de aquellos que buscan la caída de la ciudad que gobierna el joven rey. ¿Cuál es la trampa? El verdadero nombre de Ginebra. Su identidad verdadera. Nadie la conoce realmente. Ella es una sustituta, una joven que ha sacrificado todo para salvar Camelot. Para mantener a Arturo a salvo, Ginebra debe abrirse camino en una corte donde los antiguos residentes, incluida la misma familia de Arturo, quieren que las cosas continúen siendo como siempre, y los nuevos, aquellos atraídos por el sueño de Camelot, luchan por una vida mejor. Y siempre, en el corazón verde del bosque y las negras profundidades de los lagos, la magia espera al acecho para reconquistar el reino. Justas mortales, falsos caballeros y romances prohibidos no pueden compararse con la amenaza más grande: la joven de largo pelo negro que cabalga a través de la foresta oscura hacia Arturo. Porque cuando toda su existencia es una mentira, no es posible confiar ni siquiera en uno mismo.', price: 1700, img:"/img/libro8.jpg", stock: 10},
            {id: 6, name: "Lore", autor: "Alexandra Bracken", resume: 'Hace mucho tiempo, Lore Perseus huyó de esa competición brutal a raíz del sádico asesinato de su familia por parte de un linaje rival, y dejó atrás las promesas de la caza de la gloria eterna. Durante años ha intentado evadir cualquier pensamiento de venganza hacia el hombre -ahora un dios- responsable de la muerte de su familia. Sin embargo, durante el último agón en Nueva York, dos participantes le piden ayuda: Cástor, su amigo de la infancia, a quien creía muerto, y Atenea, una de las últimas diosas originales, gravemente herida. La diosa le ofrece una alianza contra su enemigo común y, además, una forma de que Lore pueda dejar el agón en el pasado para siempre. Pero la decisión de Lore de vincular su destino al de Atenea y volver a unirse a la caza tendrá un coste mortal, y puede que no sea suficiente para detener la aparición de un nuevo dios con el poder de poner a la humanidad de rodillas', price: 1900, img:"/img/libro13.jpg", stock: 10},
            {id: 7, name: "Una Luz Fuerte y Brillante", autor: "Viviana Rivero", resume: 'Corre el año 2014 y Siria continúa en una guerra sangrienta. Álvaro Sánchez, fotógrafo argentino residente en Barcelona, decide viajar para cubrir la contienda. Sus contactos lo conducen a la casa de Al Kabani, familia musulmana que le proporcionará los medios para introducirse en Duma, una de las ciudades tomadas por las fuerzas rebeldes al régimen. Pero Álvaro no imagina que ese viaje le deparará la aventura más riesgosa de su carrera y la llegada de un amor que hará tambalear todos sus paradigmas. Salma, una joven mujer árabe, lo enloquecerá. Por ella estará dispuesto a ir hasta las últimas consecuencias. Juntos experimentarán pasiones y peligros que los llevarán al límite de sus fuerzas y pondrán en juego sus vidas en medio de una vorágine de violencia y prohibiciones. La historia de la joven pareja está atravesada por otra más antigua, que transcurre durante el esplendor sirio de los años sesenta. En esa época de vaivenes políticos y duras restricciones impuestas a las mujeres irá forjándose la pequeña Nunú, cuya transformación personal marcará a fuego a Salma y Álvaro. ', price: 1800, img:"/img/libro18.jpg", stock: 10},
            {id: 8, name: "1984", autor: "George Orwell", resume: 'Escrita en 1948, esta obra denunciaba los totalitarismos de Hitler y de Stalin. Sin embargo, tanto la propaganda política de la mano de Gran Hermano -el ojo censurador- como la dominación de la población por parte del Partido poseen resonancias diacrónicas. Un clásico que percute, con fuerza renovada, en este presente en el que somos esclavos de la tecnología y de una élite sometedora. Luis Scafati se supera a sí mismo, para ofrecer uno de sus trabajos más lúcidos, críticos e impactantes de los últimos tiempos.', price: 2500, img:"/img/libroPortada.jpg", stock: 10},
            {id: 9, name: "Harry Potter: y la piedra filosofal", autor: "J.K. Rowling", resume: 'Harry Potter se ha quedado huérfano y vive en casa de sus abominables tíos y del insoportable primo Dudley. Se siente muy triste y solo, hasta que un buen día recibe una carta que cambiará su vida para siempre. En ella le comunican que ha sido aceptado como alumno en el colegio interno Hogwarts de magia y hechicería. A partir de ese momento, la suerte de Harry da un vuelco espectacular. En esa escuela tan especial aprenderá encantamientos, trucos fabulosos y tácticas de defensa contra las malas artes. Se convertirá en el campeón escolar de quidditch, especie de fútbol aéreo que se juega montado sobre escobas, y hará un puñado de buenos amigos... aunque también algunos temibles enemigos. Pero, sobre todo, conocerá los secretos que le permitirán cumplir con su destino. Pues, aunque no lo parezca a primera vista, Harry no es un chico común y corriente. ¡Es un verdadero mago!', price: 2300, img:"/img/libro22.jpg", stock: 10},
            {id: 10, name: "El Amor Cae Del Cielo", autor: "Esther Sanz", resume: '', price: 1950, img:"/img/inicio3.jpg", stock: 10},
            {id: 11, name: "Miss Marple y Trece Problemas", autor: "Agatha Christie", resume: 'Miss Marple y trece problemas, también traducido como Los casos de Miss Marple, es un libro de la escritora británica Agatha Christie publicada en 1933, que contiene trece relatos cortos, en los que cada uno de los personajes va dilucidando el respectivo misterio. Cada martes un grupo de personas se reúne para resolver supuestos misterios. Ninguno cuenta con la astucia de miss Marple. Menos imaginan lo que esas reuniones desatarán.', price: 1900, img:"/img/inicio2.jpg", stock: 10},
            {id: 12, name: "Un Marido Inventado", autor: "Julia Quinn", resume: 'Con su hermano Thomas herido en el frente de batalla y habiendo perdido a sus padres, Cecilia Harcourt tiene dos opciones no demasiado halagüeñas: mudarse junto a una tía soltera o casarse con un primo de mente retorcida. En lugar de eso, elige la tercera opción, y cruza el Atlántico dispuesta a cuidar de su hermano hasta su recuperación. Pero, tras una semana de búsqueda, no encuentra a Thomas, sino a su mejor amigo, el apuesto oficial Edward Rockesby. Está inconsciente y necesita urgentemente de sus cuidados, y Cecilia promete salvar la vida del soldado, aunque quedarse a su lado implique decir una pequeña mentira… Le dije a todo el mundo que era tu mujer.', price: 2050, img:"/img/libro 6.jpg", stock: 10},
            {id: 13, name: "Crimenes Sorprendentes De Asesinos En Serie", autor: "Ricardo Canaletti", resume: '¿Monstruos? ¿Personas comunes que se vuelven malvadas o personas que siempre esconden el deseo de matar? Los asesinos seriales no son bestias legendarias, son individuos que viven entre nosotros. Las escenas de sus crímenes parecen de película. Actúan con una violencia que no conoce límites. Los patrones de los asesinatos se repiten, calcados, uno tras otro. ¿Hasta cuándo? ¿Quién será la próxima víctima? La policía queda desconcertada, la prensa especula y la sociedad entra en pánico, porque nadie está a salvo.', price: 2000, img:"/img/libro2.jpg", stock: 10},
            {id: 14, name: "Escape", autor: "Dross", resume: 'Draco es odioso. Es un ser despreciable, incorregible, abominable. Por golpe del destino o castigo celestial, deberá salir a la calle e intentar sobrevivir a los enemigos que se ocupó de cultivar durante años. Draco tiene hambre y está solo. ¿Logrará escapar a la sentencia de muerte que yace sobre su hedionda existencia? Que arroje la primera piedra quien no haya insultado alguna vez en vano o haya creído que su situación de privilegio o comodidad duraría para siempre. En este nuevo libro de humor negro, Dross, quien lleva vendidos más de doscientos cincuenta mil ejemplares en el mundo y cuenta con una comunidad que supera los veintiún millones de seguidores, nos pone a prueba con su pluma irreverente: el que logre llegar a la última página tendrá su recompensa.', price: 1950, img:"/img/libro3.jpg", stock: 10},
            {id: 15, name: "Heartstopper", autor: "Alice Oseman", resume: 'Charlie y Nick van al mismo colegio; aunque nunca se habían cruzado hasta el día en que los hacen sentarse juntos en su grupo de estudio. Muy pronto se vuelven amigos y más pronto aún Charlie comienza a sentir cosas por Nick; aunque sabe que es un imposible. Pero el amor obra de formas inesperadas; y Nick está más interesado en Charlie de lo que ninguno de los dos puede llegar a creer.', price: 2100, img:"/img/libro4.jpg", stock: 10},
            {id: 16, name: "Brota", autor: "Guillermina Lopata", resume: 'Guillermina Lopata, psicóloga y especialista en saberes integrados (magia, chamanismo, cosmovisiones no tradicionales y espiritualidad), te propone una reconexión profunda con tu niña interior. Así lograrás sanar el pasado y dejar de existir para comenzar a vivir. Encuentra las herramientas para ser tu propia maga y atrévete a brotar. Incluye 39 ejercicios para que lleves tu magia a la acción.', price: 1700, img:"/img/libro5.jpg", stock: 10},
          ];
    const item = productsList.filter(item => item.id === parseInt(id));    
    setTimeout(() => {
        resolve(item [0]);
    }, 2000);
    });
    
    return myPromise;
}

function ItemDetailContainer() {
    const [item, setItem] = useState({});
    const { id } = useParams();

    useEffect(() => {
        getItem(id)
            .then(res => {
                setItem(res);
            })
            .catch(err => {
                console.log(err);
                alert("ERROR");
            });
    }, [id])

    return (
        <div className="itemDetail">
            <ItemDetail item={item} />
        </div>
    )
}

export default ItemDetailContainer